version: "3.9"
services:
  cassandra_1_1:
    image: cassandra:3.11.2
    networks:
      - cassandra_1
    healthcheck:
          test: [ "CMD-SHELL", "/usr/bin/cqlsh -e 'describe keyspaces'" ]
          interval: 15s
          timeout: 10s
          retries: 10
    deploy:
      resources:
        limits:
          memory: 2GB
    environment:
      - "CASSANDRA_CLUSTER_NAME=one"
      - "CASSANDRA_SEEDS=cassandra_1_1"
      - "CASSANDRA_HOST=cassandra_1_1"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=250M"
  cassandra_1_2:
    image: cassandra:3.11.2
    networks:
      - cassandra_1
    depends_on:
      cassandra_1_1:
        condition: service_healthy
    healthcheck:
          test: [ "CMD-SHELL", "/usr/bin/cqlsh -e 'describe keyspaces'" ]
          interval: 15s
          timeout: 10s
          retries: 10
    deploy:
      resources:
        limits:
          memory: 2GB
    environment:
      - "CASSANDRA_CLUSTER_NAME=one"
      - "CASSANDRA_SEEDS=cassandra_1_1"
      - "CASSANDRA_HOST=cassandra_1_2"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=250M"
  cassandra_1_3:
    image: cassandra:3.11.2
    networks:
      - cassandra_1
    depends_on:
      cassandra_1_2:
        condition: service_healthy
    healthcheck:
          test: [ "CMD-SHELL", "/usr/bin/cqlsh -e 'describe keyspaces'" ]
          interval: 15s
          timeout: 10s
          retries: 10
    deploy:
      resources:
        limits:
          memory: 2GB
    environment:
      - "CASSANDRA_CLUSTER_NAME=one"
      - "CASSANDRA_SEEDS=cassandra_1_1"
      - "CASSANDRA_HOST=cassandra_1_3"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=250M"
  cassandra_2_1:
    image: cassandra:3.11.2
    networks:
      - cassandra_2
    healthcheck:
          test: [ "CMD-SHELL", "/usr/bin/cqlsh -e 'describe keyspaces'" ]
          interval: 15s
          timeout: 10s
          retries: 10
    deploy:
      resources:
        limits:
          memory: 2GB
    environment:
      - "CASSANDRA_CLUSTER_NAME=two"
      - "CASSANDRA_SEEDS=cassandra_2_1"
      - "CASSANDRA_HOST=cassandra_2_1"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=250M"
  toxiproxy_2_1:
    image: "shopify/toxiproxy"
    networks:
      - cassandra_2
    depends_on:
      - cassandra_2_1
  # We created proxy configuration from another ephermal container
  toxiproxy-config_2_1:
    image: "shopify/toxiproxy"
    networks:
      - cassandra_2
    depends_on:
      toxiproxy_2_1:
        condition: service_started
    entrypoint: >
      sh -c "/go/bin/toxiproxy-cli -h   toxiproxy_2_1:8474 create cassandra --listen 0.0.0.0:9042 --upstream cassandra_2_1:9042;
      /go/bin/toxiproxy-cli -h toxiproxy_2_1:8474 toxic add -t latency -a latency=3000 cassandra"
  cassandra_2_2:
    image: cassandra:3.11.2
    networks:
      - cassandra_2
    depends_on:
      cassandra_2_1:
        condition: service_healthy
    healthcheck:
          test: [ "CMD-SHELL", "/usr/bin/cqlsh -e 'describe keyspaces'" ]
          interval: 15s
          timeout: 10s
          retries: 10
    deploy:
      resources:
        limits:
          memory: 2GB
    environment:
      - "CASSANDRA_CLUSTER_NAME=two"
      - "CASSANDRA_SEEDS=cassandra_2_1"
      - "CASSANDRA_HOST=cassandra_2_2"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=250M"
  toxiproxy_2_2:
    image: "shopify/toxiproxy"
    networks:
      - cassandra_2
    depends_on:
      - cassandra_2_2
  # We created proxy configuration from another ephermal container
  toxiproxy-config_2_2:
    image: "shopify/toxiproxy"
    networks:
      - cassandra_2
    depends_on:
      toxiproxy_2_2:
        condition: service_started
    entrypoint: >
      sh -c "/go/bin/toxiproxy-cli -h   toxiproxy_2_2:8474 create cassandra --listen 0.0.0.0:9042 --upstream cassandra_2_2:9042;
      /go/bin/toxiproxy-cli -h toxiproxy_2_2:8474 toxic add -t latency -a latency=3000 cassandra"
  cassandra_2_3:
    image: cassandra:3.11.2
    networks:
      - cassandra_2
    depends_on:
      cassandra_2_2:
        condition: service_healthy
    healthcheck:
          test: [ "CMD-SHELL", "/usr/bin/cqlsh -e 'describe keyspaces'" ]
          interval: 15s
          timeout: 10s
          retries: 10
    deploy:
      resources:
        limits:
          memory: 2GB
    environment:
      - "CASSANDRA_CLUSTER_NAME=two"
      - "CASSANDRA_SEEDS=cassandra_2_1"
      - "CASSANDRA_HOST=cassandra_2_3"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=250M"
  toxiproxy_2_3:
    image: "shopify/toxiproxy"
    networks:
      - cassandra_2
    depends_on:
      - cassandra_2_3
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/nc -vz -w 1 127.0.0.1 9042" ]
  # We created proxy configuration from another ephermal container
  toxiproxy-config_2_3:
    image: "shopify/toxiproxy"
    networks:
      - cassandra_2
    depends_on:
      toxiproxy_2_3:
        condition: service_started
    entrypoint: >
      sh -c "/go/bin/toxiproxy-cli -h   toxiproxy_2_3:8474 create cassandra --listen 0.0.0.0:9042 --upstream cassandra_2_3:9042;
      /go/bin/toxiproxy-cli -h toxiproxy_2_3:8474 toxic add -t latency -a latency=3000 cassandra"
  proxy_1:
    image: datastax/zdm-proxy:2.1.0
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/nc -vz -w 1 127.0.0.1 9042"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      cassandra_1:
      cassandra_2:
      proxies:
        ipv4_address: 172.16.238.10
    depends_on:
        cassandra_1_1:
          condition: service_healthy
        cassandra_1_2:
          condition: service_healthy
        cassandra_1_3:
          condition: service_healthy
        cassandra_2_1:
          condition: service_healthy
        cassandra_2_2:
          condition: service_healthy
        cassandra_2_3:
          condition: service_healthy
        toxiproxy-config_2_1:
          condition: service_completed_successfully
        toxiproxy-config_2_2:
          condition: service_completed_successfully
        toxiproxy-config_2_3:
          condition: service_completed_successfully
    environment:
      - ZDM_PRIMARY_CLUSTER=ORIGIN
      - ZDM_READ_MODE=PRIMARY_ONLY
      - ZDM_ORIGIN_CONTACT_POINTS=cassandra_1_1,cassandra_1_2,cassandra_1_3
      - ZDM_TARGET_CONTACT_POINTS=toxiproxy_2_1,toxiproxy_2_2,toxiproxy_2_3
      - ZDM_ORIGIN_PORT=9042
      - ZDM_TARGET_PORT=9042
      - ZDM_LOG_LEVEL=INFO
      - ZDM_TARGET_USERNAME=cassandra
      - ZDM_TARGET_PASSWORD=cassandra
      - ZDM_ORIGIN_USERNAME=cassandra
      - ZDM_ORIGIN_PASSWORD=cassandra
      - ZDM_PROXY_LISTEN_PORT=9042
      - ZDM_PROXY_TOPOLOGY_ADDRESSES=172.16.238.10,172.16.238.11,172.16.238.12
      - ZDM_PROXY_TOPOLOGY_INDEX=0
  proxy_2:
    image: datastax/zdm-proxy:2.1.0
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/nc -vz -w 1 127.0.0.1 9042" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      cassandra_1:
      cassandra_2:
      proxies:
        ipv4_address: 172.16.238.11
    depends_on:
      cassandra_1_1:
        condition: service_healthy
      cassandra_1_2:
        condition: service_healthy
      cassandra_1_3:
        condition: service_healthy
      cassandra_2_1:
        condition: service_healthy
      cassandra_2_2:
        condition: service_healthy
      cassandra_2_3:
        condition: service_healthy
      toxiproxy-config_2_1:
        condition: service_completed_successfully
      toxiproxy-config_2_2:
        condition: service_completed_successfully
      toxiproxy-config_2_3:
        condition: service_completed_successfully
    environment:
      - ZDM_PRIMARY_CLUSTER=ORIGIN
      - ZDM_READ_MODE=PRIMARY_ONLY
      - ZDM_ORIGIN_CONTACT_POINTS=cassandra_1_1,cassandra_1_2,cassandra_1_3
      - ZDM_TARGET_CONTACT_POINTS=toxiproxy_2_1,toxiproxy_2_2,toxiproxy_2_3
      - ZDM_ORIGIN_PORT=9042
      - ZDM_TARGET_PORT=9042
      - ZDM_LOG_LEVEL=INFO
      - ZDM_TARGET_USERNAME=cassandra
      - ZDM_TARGET_PASSWORD=cassandra
      - ZDM_ORIGIN_USERNAME=cassandra
      - ZDM_ORIGIN_PASSWORD=cassandra
      - ZDM_PROXY_LISTEN_PORT=9042
      - ZDM_PROXY_TOPOLOGY_ADDRESSES=172.16.238.10,172.16.238.11,172.16.238.12
      - ZDM_PROXY_TOPOLOGY_INDEX=1
  proxy_3:
    image: datastax/zdm-proxy:2.1.0
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/nc -vz -w 1 127.0.0.1 9042" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      cassandra_1:
      cassandra_2:
      proxies:
        ipv4_address: 172.16.238.12
    depends_on:
      cassandra_1_1:
        condition: service_healthy
      cassandra_1_2:
        condition: service_healthy
      cassandra_1_3:
        condition: service_healthy
      cassandra_2_1:
        condition: service_healthy
      cassandra_2_2:
        condition: service_healthy
      cassandra_2_3:
        condition: service_healthy
      toxiproxy-config_2_1:
        condition: service_completed_successfully
      toxiproxy-config_2_2:
        condition: service_completed_successfully
      toxiproxy-config_2_3:
        condition: service_completed_successfully
    environment:
      - ZDM_PRIMARY_CLUSTER=ORIGIN
      - ZDM_READ_MODE=PRIMARY_ONLY
      - ZDM_ORIGIN_CONTACT_POINTS=cassandra_1_1,cassandra_1_2,cassandra_1_3
      - ZDM_TARGET_CONTACT_POINTS=toxiproxy_2_1,toxiproxy_2_2,toxiproxy_2_3
      - ZDM_ORIGIN_PORT=9042
      - ZDM_TARGET_PORT=9042
      - ZDM_LOG_LEVEL=INFO
      - ZDM_TARGET_USERNAME=cassandra
      - ZDM_TARGET_PASSWORD=cassandra
      - ZDM_ORIGIN_USERNAME=cassandra
      - ZDM_ORIGIN_PASSWORD=cassandra
      - ZDM_PROXY_LISTEN_PORT=9042
      - ZDM_PROXY_TOPOLOGY_ADDRESSES=172.16.238.10,172.16.238.11,172.16.238.12
      - ZDM_PROXY_TOPOLOGY_INDEX=2
  cassandra_client:
    build: client
    image: client
    networks:
      - cassandra_1
    command:  cassandra_1_1 cassandra_1_2 cassandra_1_3
    depends_on:
      cassandra_1_1:
        condition: service_healthy
      cassandra_1_2:
        condition: service_healthy
      cassandra_1_3:
        condition: service_healthy
  proxy_client:
    build: client
    image: client
    command:  proxy_1 proxy_2 proxy_3
    networks:
      - proxies
    depends_on:
      proxy_1:
        condition: service_healthy
      proxy_2:
        condition: service_healthy
      proxy_3:
        condition: service_healthy
networks:
  cassandra_1:
  cassandra_2:
  proxies:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"